### ISSUE TITLE
Merge requests fail with error 500 for some projects

### ISSUE THREAD

**Issue by danielran** [gitlabhq/gitlabhq#7237]
I've been trying to figure out this one for days. Several other issues seem similar but I've had no luck with any of the proposed solutions (rebuilding satellites, manually cloning into satellite repo, running `bundle install` etc.).

Attempting to merge certain branches (most but not all) on certain projects (most but not all) results in 500 errors. There seems to be no correlation between whether a repository has seen any change since the upgrade to 7.0.

production.log
```
Processing by Projects::MergeRequestsController#new as HTML
Parameters: {"utf8"=>"✓", "merge_request"=>{"source_project_id"=>"#", "source_branch"=>"branchName", "target_project_id"=>"#", "target_branch"=>"master"}, "project_id"=>"<repo-group>/<repo>"}
Completed 500 Internal Server Error in 445ms
NoMethodError (undefined method `reduce' for false:FalseClass):
app/models/commit.rb:26:in `diff_line_count'
app/controllers/projects/merge_requests_controller.rb:94:in `new'
```

githost.log
```
July 02, 2014 06:38 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/<repo-group>/<repo>/.git merge-base origin/master source/branchName
```

It also contains a few instances of this.
```
July 01, 2014 14:26 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/<repo>/.git branch -D master
error: Cannot delete the branch 'master' which you are currently on.
```

Which is odd since no one is trying to delete the master branch.

This is the output of `gitlab:check`. All green.
```
Instance method "lock!" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.6 ? ... OK (1.9.6)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ...
[All repos OK]
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /home/git/repositories: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.4
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...
[All repos OK]
Projects have satellites? ...
[All repos OK]
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.1)

Checking GitLab ... Finished
```

Environment.
```
Instance method "lock!" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.

System information
System:         Ubuntu 14.04
Current User:   git
Using RVM:      no
Ruby Version:   2.1.2p95
Gem Version:    2.2.2
Bundler Version:1.6.3
Rake Version:   10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:        7.0.0
Revision:       de9bf7d
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            http://<gitlab>
HTTP Clone URL: http://<gitlab>/some-project.git
SSH Clone URL:  git@<gitlab>:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.6
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

I've tried everything I can think of. I think it's still a synchronicity problem between the satellites and actual repositories but even deleting `gitlab-satellites` and recreating them doesn't solve it.

**Comment by rhlowery** [comment]
+1 getting the issue with a project in 7.6.2_omnibus.5.3.0.ci.1-1.el6

**Comment by azmelanar** [comment]
+1 getting issue with GitLab 7.7.2

Tried clean up satellites, but issue re-appeared.

```
$ grep -A 3 satellites config/gitlab.yml
  satellites:
    path: /home/git/gitlab-satellites/
    timeout: 30
```

```
Started GET "/user1/myrepo/merge_requests/23/automerge_check" for <ip> at 2015-02-16 10:50:31 +0200
Processing by Projects::MergeRequestsController#automerge_check as JSON
  Parameters: {"project_id"=>"user1/myrepo", "id"=>"23"}
Completed 500 Internal Server Error in 57ms

Grit::Git::CommandFailed (Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/user1/myrepo/.git --work-tree=/home/git/gitlab-satellites/user1/myrepo branch -D dev

error: Cannot delete the branch 'dev' which you are currently on.
):
  lib/gitlab/satellite/satellite.rb:107:in `block in delete_heads!'
  lib/gitlab/satellite/satellite.rb:107:in `each'
  lib/gitlab/satellite/satellite.rb:107:in `delete_heads!'
  lib/gitlab/satellite/satellite.rb:23:in `clear_and_update!'
  lib/gitlab/satellite/action.rb:40:in `prepare_satellite!'
  lib/gitlab/satellite/merge_action.rb:15:in `block in can_be_merged?'
  lib/gitlab/satellite/action.rb:24:in `block (2 levels) in in_locked_and_timed_satellite'
  lib/gitlab/satellite/satellite.rb:56:in `block in lock'
  lib/gitlab/satellite/satellite.rb:53:in `open'
  lib/gitlab/satellite/satellite.rb:53:in `lock'
  lib/gitlab/satellite/action.rb:23:in `block in in_locked_and_timed_satellite'
  lib/gitlab/satellite/action.rb:22:in `in_locked_and_timed_satellite'
  lib/gitlab/satellite/merge_action.rb:14:in `can_be_merged?'
  app/models/merge_request.rb:176:in `check_if_can_be_merged'
  app/controllers/projects/merge_requests_controller.rb:106:in `automerge_check'
```

```
$ bundle exec rake gitlab:check RAILS_ENV=production                                                 
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.4.2 ? ... OK (2.4.2)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 

Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
        /home/git/repositories: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.2.12
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ...
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 

Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.5)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (2.1.1)

Checking GitLab ... Finished
```

```
$ bundle exec rake gitlab:env:info RAILS_ENV=production                                              
System information
System:         Ubuntu 12.04
Current User:   git
Using RVM:      yes
RVM Version:    1.25.34
Ruby Version:   2.1.5p273
Gem Version:    2.4.3
Bundler Version:1.8.0
Rake Version:   10.3.2
Sidekiq Version: 2.17.8

GitLab information
Version:        7.7.2
Revision:       98ef392
Directory:      /home/git/gitlab
DB Adapter:     postgresql
URL:            https://<gitlab>
HTTP Clone URL: https://<gitlab>/some-project.git
SSH Clone URL:  git@<gitlab>:some-project.git
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        2.4.2
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by blaskovicz** [comment]
Happening to our installation as well with two branches in the same repo (_non-master -> master_).

 Component | Version 
--------------- | --------- 
GitLab|7.2.1
GitLab Shell|1.9.7
GitLab API|v3
Ruby|2.1.0p0
Rails|4.1.1

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by babltiga** [comment]
@Razer6  Same issue with the latest 7.10.4, in which version does this issue fixed ?

**Comment by nlescure** [comment]
@Razer6 Can you give us the link to the patch please ?
