### ISSUE TITLE
GitLab 500: We're sorry, but something went wrong

### ISSUE THREAD

**Issue by YURSHAT** [gitlabhq/gitlabhq#8281]
Hello
GitLab: 7.4.0.rc1
OS: Debian 7
2GB RAM

After upgrading GitLab to 7.4  watch permanent errors 500. The error appears on all pages, and very often. After checking app status - all green

**Comment by Razer6** [comment]
Closing this because this seems to be a HW issue. Other errors not related to this issue.

**Comment by lowlander** [comment]
Are you sure this should be closed ? I am running into similar problems with a custom linux tree.  I am using gitlab-7.8.2_omnibus.1-1.el7.x86_64.rpm

The bad thing is, this was an initial evaluation if gitlab would be useful to us, and the first repo we imported gives us an error 500 :disappointed:

----
```
Started GET "/upstream-sources/linux/commits/master" for 127.0.0.1 at 2015-03-07 12:05:28 +0100
Processing by Projects::CommitsController#show as HTML
Parameters: {"project_id"=>"upstream-sources/linux", "id"=>"master"}
Completed 500 Internal Server Error in 256ms
ActionView::Template::Error (undefined method `chomp' for nil:NilClass):
12: = nav_link(controller: :tags) do
13: = link_to project_tags_path(@project) do
14: Tags
15: %span.badge.js-totaltags-count= @repository.tags.length
app/models/repository.rb:169:in `method_missing'
app/views/projects/commits/_head.html.haml:15:in `block (2 levels) in _app_views_projects_commits__head_html_haml___1954060998738350391_114301960'
app/helpers/application_helper.rb:280:in `link_to'
app/views/projects/commits/_head.html.haml:13:in `block in _app_views_projects_commits__head_html_haml___1954060998738350391_114301960'
app/helpers/tab_helper.rb:55:in `nav_link'
app/views/projects/commits/_head.html.haml:12:in `_app_views_projects_commits__head_html_haml___1954060998738350391_114301960'
app/views/projects/commits/show.html.haml:1:in `_app_views_projects_commits_show_html_haml___2103597451904728331_114099860'
app/controllers/projects/commits_controller.rb:18:in `show'

```

**Comment by Razer6** [comment]
@lowlander You're facing a different error. The upcoming 7.9 release will have several improvements for very large repositories such as the linux kernel.

**Comment by lowlander** [comment]
OK I will retry when the 7.9 omnibus is released, tanks for the info.
