### ISSUE TITLE
[v7.13] ActionView::Template::Error (undefined method `sha' for nil:NilClass)

### ISSUE THREAD

**Issue by elboletaire** [gitlabhq/gitlabhq#9484]
After upgrading gitlab to 7.13 I started getting 500 errors on some of my projects. If I run the gitlab tests it says everything is ok.

Here's what the `production.log` states about my error:

    Completed 500 Internal Server Error in 992ms (ActiveRecord: 330.5ms)
    ActionView::Template::Error (undefined method `sha' for nil:NilClass):
    7: = link_to namespace_project_edit_blob_path(@project.namespace, @project, tree_join(@repository.root_ref, readme.name)), class: 'light' do
    8: %i.fa.fa-pencil
    9: .wiki
    10: = cache(readme_cache_key) do
    11: = render_readme(readme)
    12: - else
    13: %h3.page-title
    app/helpers/projects_helper.rb:277:in `readme_cache_key'
    app/views/projects/_readme.html.haml:10:in `_app_views_projects__readme_html_haml___2518100473481433653_69882723290400'
    app/views/projects/show.html.haml:47:in `_app_views_projects_show_html_haml___991411998595127387_69882660500980'
    app/controllers/projects_controller.rb:85:in `block (2 levels) in show'
    app/controllers/projects_controller.rb:79:in `show'

**Comment by gtrias** [comment]
Affected by this issue >.<

**Comment by stanhu** [comment]
This could happen if the HEAD branch does not exist. Can you show the output of `git ls-remote .` for these repositories?

**Comment by elboletaire** [comment]
Head branch exists, but it's not the master branch (it is develop instead):

    b1ba148f3fdd60318d9320b1656904728b14c9dc    HEAD
    b1ba148f3fdd60318d9320b1656904728b14c9dc    refs/heads/develop
    0dd8f0f5ae109831082c31c5d43be57d1447f6bd    refs/heads/f/remove-menu-aside
    b1ba148f3fdd60318d9320b1656904728b14c9dc    refs/remotes/origin/develop
    73a2761ad2e8971eec9719d917a81fbbde87be2a    refs/remotes/upstream/3.1
    e708b89badba28f0ad9d455b645c4d84eb327f7b    refs/remotes/upstream/3.1-mailer
    48b94d69cc0d62eccfa9ef500a52e66f615f4122    refs/remotes/upstream/master
    037fe36b145d48f6e703736e69bb41a2b935f2d5    refs/remotes/upstream/revert-244-jsonview-serialization
    5797727d03addf0cac24b9849f2a9203d640ae19    refs/tags/3.0.0
    60b6c2d671d277b35d497a5c2792bd9787fe149a    refs/tags/3.0.0^{}
    6dafaddec83a6c4e951c2d7411aa2c997ab64da5    refs/tags/3.0.0-RC1
    4b1ec739b56a437a454470f05768189f63619bbe    refs/tags/3.0.0-RC1^{}
    54ee8af15786ff12f4f0ac8b8ae45c4e9190d49e    refs/tags/3.0.0-RC2
    7639bdbf4761d867dcbb5abcbe36f74e97025fea    refs/tags/3.0.0-RC2^{}
    4707febef3a2fd11a84bc6d44c407048c67e0d4f    refs/tags/3.0.0-alpha1
    3a74fb5363be64d238a25696b79bd3a748cfe605    refs/tags/3.0.0-alpha1^{}
    e9d321057f8e2ddb2a43620203f756a0d8c447ab    refs/tags/3.0.0-alpha2
    a031369b9b22f22e631d4e48aabbf0e375e7b069    refs/tags/3.0.0-alpha2^{}
    03f52660fe79ff6792ffce58f75c5799a98ac63d    refs/tags/3.0.0-beta1
    6cda2f80f0e54a86df1e37b40eb9ca40f5b13e1d    refs/tags/3.0.0-beta1^{}
    abb68ac634e288148d28459cfd2521465ea0f1b7    refs/tags/3.0.0-beta2
    7e14c566923b4f0a25fd6e5c30e3b1c7c2ba823f    refs/tags/3.0.0-beta2^{}
    4dc504803dde751fb9e2ea2f052cc5bea438bb80    refs/tags/3.0.0-beta3
    64ea4057e6dd30263c4de537b0ca1fc26d7ea058    refs/tags/3.0.0-beta3^{}
    921cf311d6d99581b38c0e0587f02a5fff902adf    refs/tags/3.0.0-dev2
    24371d449e533d9e8b9a5c396d01de76dc2f912a    refs/tags/3.0.0-dev2^{}
    170d8a0ab2b1e214b9a9ac5d52d3f4435ca199a7    refs/tags/3.0.0-dev3
    0144de3047812760435b6e1dd75932251dc4424b    refs/tags/3.0.0-dev3^{}
    9c24d004f4de68a9412a49e3474bf648266bf95b    refs/tags/3.0.1
    dffe0f6805a65630c96893e82dd075d722406ee6    refs/tags/3.0.2
    ef46abb40f2c0d5078e1b6db1a167ce89cbcdd7c    refs/tags/3.0.2^{}
    68cfee97f0d8cd8fd4b1b3a27840ca4be60a6582    refs/tags/3.0.3

**Comment by stanhu** [comment]
That's odd--I wasn't able to replicate the error when HEAD pointed to `develop`, but I had no issues getting the issue when I deleted HEAD outright.

**Comment by stanhu** [comment]
If you have access to the raw repository on the remote (e.g. login to the machine, cd into `/var/opt/gitlab/git-data/repositories/XXX`), can you try `ls-remote .` there?

**Comment by elboletaire** [comment]
Sure (I got the old installation, so I've cd into `/home/git/gitlab-satellites/group/repo` instead):

    37f7d2ace0f899a8ba99f4eee10fdcfabb0d8216	refs/remotes/origin/develop

It only appears this, is this normal? :sweat_smile:

**Comment by stanhu** [comment]
Oh, wow. How did that happen? That's not normal at all. :) I have [submitted a fix](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1041) that will prevent GitLab from hitting the error 500, but I'm really puzzled why your repo is in that state.

**Comment by stanhu** [comment]
Actually, it's normal for the satellites not to have a HEAD and to look like that. Do you have access the main repository for your project?

**Comment by elboletaire** [comment]
Hey Stan I'm sorry but I cannot check this until monday, as this only occurs on my work's gitlab.

BTW, @gtrias will check it for me, because I'm on vacation.

Thanks for the fast response and action :smile:

**Comment by gtrias** [comment]
Yeah it works now, good job and thanks @stanhu :)
