### ISSUE TITLE
500 error on /users/sign_in page since upgrade from 8.0.5 to 8.1

### ISSUE THREAD

**Issue by schmittner** [gitlabhq/gitlabhq#9781]
Hi,
I'm running the omnibus package on Debian 7 (Debian's nginx instead of omnibus nginx), and since upgrade from 8.0.5 to 8.1 (and now also 8.1.2), I receive a '500' on the /users/sign_in page. Already logged in users are able to browse GitLab without a problem.

Neither `/var/log/gitlab/gitlab-rails/production.log` nor `/var/log/gitlab/unicorn/unicorn_stderr.log` show anything unusual. `gitlab-ctl reconfigure` does not help. A downgrade back to 8.0.5 is my current workaround.

Any ideas?

**Comment by stanhu** [comment]
Did all your migrations run successfully? You may want to run `sudo gitlab-rake gitlab:check`.

**Comment by schmittner** [comment]
I found the cause. Until now, I used a custom Markdown welcome page including an image like so:
```
![img](/abs/path/to/img.png)
```
This causes an error
```
Started GET "/users/sign_in" for ::ffff:130.83.29.38 at 2015-10-30 13:29:59 +0100
Processing by SessionsController#new as HTML
Completed 500 Internal Server Error in 44ms (ActiveRecord: 2.1ms)

ActionView::Template::Error (undefined method `path_with_namespace' for nil:NilClass):
    25:                 Each project can also have an issue tracker and a wiki.
    26:
    27:             - if extra_sign_in_text.present?
    28:               = markdown(extra_sign_in_text)
    29:
    30:     %hr
    31:     .container
  lib/gitlab/markdown/upload_link_filter.rb:36:in `build_url'
  lib/gitlab/markdown/upload_link_filter.rb:31:in `process_link_attr'
  lib/gitlab/markdown/upload_link_filter.rb:18:in `block in call'
  lib/gitlab/markdown/upload_link_filter.rb:17:in `call'
  lib/gitlab/markdown.rb:127:in `gfm'
  lib/gitlab/markdown.rb:24:in `render'
  app/helpers/gitlab_markdown_helper.rb:61:in `markdown'
  app/views/layouts/devise.html.haml:28:in `_app_views_layouts_devise_html_haml__1478332617046679184_57059300'
  app/controllers/sessions_controller.rb:15:in `new'
```
So it appears, that the current Markdown parser is broken for absolute paths.
Including the full path including domain solves the issue:
```
![img](https://domain.tld/abs/path/to/img.png)
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
