### ISSUE TITLE
7.5: Error 500 when displaying tree from TAG with git submodules

### ISSUE THREAD

**Issue by jlferrer** [gitlabhq/gitlabhq#8411]
Hi,

After upgrading to 7.5, projects with git submodules result in 500 error when selecting a TAG in the tree viewer: URL: https://GITLABSERVER/PROJECT/tree/TAG.

Branches of those projects (with git submodules) work fine as expected.

The submodules in these cases are local projects in our GITLAB server.

Here's the output log:
```
Processing by Projects::TreeController#show as HTML
Parameters: {"project_id"=>"PROJECT_NAME", "id"=>"TAG"}
Completed 500 Internal Server Error in 34ms
ActionView::Template::Error (undefined method `tree' for #<Rugged::Tag::Annotation:0x007f3a4109afd8>):
1: - tree, commit = submodule_links(submodule_item)
2: %tr{ class: "tree-item" }
3: %td.tree-item-file-name
4: %i.fa.fa-archive
app/models/repository.rb:162:in `method_missing'
app/models/repository.rb:228:in `submodule_url_for'
app/helpers/submodule_helper.rb:6:in `submodule_links'
app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml___3920190346442375826_69944086760620'
app/helpers/tree_helper.rb:19:in `render_tree'
app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml__1134919166262974957_69944086366800'
app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__1840674113715656229_69944085778700'
app/controllers/projects/tree_controller.rb:13:in `show'
```

**Comment by Razer6** [comment]
Pending MR https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/607
