### ISSUE TITLE
New issue => HTTP-Statuscode 500

### ISSUE THREAD

**Issue by DasLampe** [gitlabhq/gitlabhq#8647]
After update to 7.7.1 I get an 500 if I try to create a new issue.

production.log
```
Started POST "/[namespace]/[repo]/issues" for 127.0.0.1 at 2015-01-24 13:48:28 +0100
Processing by Projects::IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[token]", "issue"=>{"title"=>"[msg]", "assignee_id"=>"8", "label_ids"=>["", "59", "64"]}, "project_id"=>"[namespace]/[repo]"}
Completed 500 Internal Server Error in 175ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/services/issues/create_service.rb:9:in `execute'
  app/controllers/projects/issues_controller.rb:58:in `create'
```

ruby version: 2.2.0p0 (2014-12-25 revision 49005)

**Comment by DasLampe** [comment]
Okay, my fault.
Ruby 2.2 isn't supported.
Ruby 2.1 works.
