### ISSUE TITLE
[Gitlab 7.1] Undefined local viariables after upgrade to 7.1

### ISSUE THREAD

**Issue by arruor** [gitlabhq/gitlabhq#7360]
I'm experiencing some troubles after upgrade of Gitlab CE  from 7.0.0 to 7.1.0. 
To perform upgrade I was using upgrader script as described in https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/upgrader.md. 
Upgrade just ran fine without any troubles. When gitlab service was restarted it starts to shown "500 We're sorry, but something went wrong" instead of login page.
Here is a snip from production.log:
```
Started GET "/users/sign_in" for 1.1.1.1 at 2014-07-23 10:13:44 +0000
Processing by Devise::SessionsController#new as HTML
Completed 500 Internal Server Error in 172ms

ActionView::Template::Error (undefined local variable or method `brand_title' for #<#<Class:0x007ffb06636bf0>:0x007ffb05f9aa30>):
     6:     .container
     7:       .content
     8:         .login-title
     9:           %h1= brand_title
    10:     %hr
    11:     .container
    12:       .content
  app/views/layouts/devise.html.haml:9:in `_app_views_layouts_devise_html_haml__1381480686227818264_70358060381460'
```
It seems that variables described in app/helpers/appearances_helper.rb is not passed to devise layout.
I've managed to find quick & dirty fix for this - I need to define same variables in app/views/layouts/devise.html.haml.

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
