### ISSUE TITLE
Error 500 everyhwere

### ISSUE THREAD

**Issue by egon0** [gitlabhq/gitlabhq#9003]
After updating my omnibus-installation to 7.9.0 i get only error 500 everywhere.

```
NoMethodError (undefined method `push_events=' for #<GitlabIssueTrackerService:0x000000066fd140>):
  app/models/project.rb:329:in `default_issue_tracker'
  app/controllers/application_controller.rb:190:in `add_gon_variables'
```

**Comment by egon0** [comment]
Ok, after running the migrations again via 

```gitlab-rake db:migrate
