### ISSUE TITLE
Another 500 when adding key

### ISSUE THREAD

**Issue by rulatir** [gitlabhq/gitlabhq#8567]
This is distinct from #7185 and probably has nothing to do with memory.

NoMethodError (undefined method `name' for nil:NilClass):
  app/controllers/projects/deploy_keys_controller.rb:27:in `create'

That's the entire backtrace in the log file. I don't see identifier "name" anywhere near that line, and I don't understand Ruby enough to delve into this.

**Comment by rkorn86** [comment]
Same error here using firefox to eleminate chrome issue.
Using ruby 2.2.0 and GitLab 7.6.1. Any more infos needed?

**Comment by eminden** [comment]
I am having the same errors, admin cannot see the groups and adding a deployment is not possible, any idea how to fix?

Started GET "/admin/groups" for IP at 2015-01-15 11:49:00 +0000
Processing by Admin::GroupsController#index as HTML
Completed 500 Internal Server Error in 18ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    35:           = truncate group.description, length: 150
    36:       .clearfix
    37:         %p.light
    38:           #{pluralize(group.members.size, 'member')}, #{pluralize(group.projects.count, 'project')}
    39: 
    40: 
    41: = paginate @groups, theme: "gitlab"
  app/views/admin/groups/index.html.haml:38:in `block in _app_views_admin_groups_index_html_haml___416783796898885497_69894312789120'
  app/views/admin/groups/index.html.haml:18:in `_app_views_admin_groups_index_html_haml___416783796898885497_69894312789120'


  Started PUT "/developers/upload/deploy_keys/71/enable" for IP at 2015-01-15 11:49:46 +0000
Processing by Projects::DeployKeysController#enable as HTML
  Parameters: {"authenticity_token"=>"LZPI3gO0+5mH1o79dKcRh5B9bqMXt5qgwELy8VIfBXE=", "project_id"=>"developers/upload", "id"=>"71"}
Completed 500 Internal Server Error in 261ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/controllers/projects/deploy_keys_controller.rb:45:in `enable'

all lines are green on rake gitlab:check task. here is the system details,

System information
System:		Debian 6.0.10
Current User:	git
Using RVM:	no
Ruby Version:	2.2.0p0
Gem Version:	2.4.5
Bundler Version:1.7.11
Rake Version:	10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:	7.6.2
Revision:	16f0968
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		http://gitlab
HTTP Clone URL:	http://gitlab/some-project.git
SSH Clone URL:	git@gitlab:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.4.0
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git

Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.2.0)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.2)

**Comment by simonzack** [comment]
I'm getting similar errors on ruby 2.2, although while adding tags to issues. The log shows:

    Completed 500 Internal Server Error in 53ms

    NoMethodError (undefined method `name' for nil:NilClass):
      app/services/issues/update_service.rb:17:in `execute'
      app/controllers/projects/issues_controller.rb:77:in `update'

**Comment by argosback** [comment]
I 've this error when I try to add a `deploy key`

> HTTP 500

```
Started POST "/web/vmc-development/deploy_keys" for IPADDRESS at 2015-01-22 16:22:20 -0500
Processing by Projects::DeployKeysController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...=", "deploy_key"=>{"title"=>"webserver", "key"=>"ssh-rsa ... root@srv.local"}, "project_id"=>"web/project"}
Completed 500 Internal Server Error in 29ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/controllers/projects/deploy_keys_controller.rb:27:in `create'
````
Gitlab info

> sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production

```
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/fog-core-1.21.1/lib/fog/core/collection.rb:148: warning: circular argument reference - filters
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/fog-1.21.0/lib/fog/rackspace/mock_data.rb:43: warning: duplicated key at line 81 ignored: "name"

System information
System:         Ubuntu 14.04
Current User:   git
Using RVM:      no
Ruby Version:   2.2.0p0
Gem Version:    2.4.5
Bundler Version:1.7.12
Rake Version:   10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:        7.7.0.rc4
Revision:       31901f3
Directory:      /home/git/gitlab
DB Adapter:     postgresql
URL:            http://git.vmcdevelopment.com
HTTP Clone URL: http://git.vmcdevelopment.com/some-project.git
SSH Clone URL:  git@git.vmcdevelopment.com:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        2.4.1
Repositories:   /var/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by therealshredder** [comment]
I experience the same problem with the exact same error message in production.log.

```
Processing by Projects::DeployKeysController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"RKLS...", "deploy_key"=>{"title"=>"server", "key"=>"ssh-rsa AAAA... name"}, "project_id"=>"xxx"}
Completed 500 Internal Server Error in 329ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/controllers/projects/deploy_keys_controller.rb:27:in `create'
```

**Comment by chulkilee** [comment]
Same error in different case - adding label. Running gitlab 7.7.1 with ruby 2.2.0 using rbenv

```
NoMethodError (undefined method `name' for nil:NilClass):
  app/services/issues/update_service.rb:17:in `execute'
  app/controllers/projects/issues_controller.rb:75:in `update'
```

@rulatir  could you update the title to include Ruby 2.2.0?

**Comment by icyleaf** [comment]
me too, Running gitlab 7.7.1 with ruby 2.2.0(system)

from related code file, i can't find any varibale call `name` method.

**Comment by drmonty** [comment]
as noted in #8624, #8685, #8671 ruby 2.2.x is not supported yet (but I'm using it anyway, too (thanks to archlinux rolling-release :ghost:)).

@randx Any plans to support ruby 2.2.x with gitlab 7.8?

**Comment by randx** [comment]
@drmonty its not on our radar now. We need to update some gems to get it work with ruby 2.2. But we will do it at certain point

**Comment by drmonty** [comment]
thanks @randx :)

**Comment by Razer6** [comment]
Closing this as this is a ruby 2.2 issue which is not supported right now

**Comment by manhnv85** [comment]
Help me!
I'm new gitlab 
My verion is GitLab 7.11.4
After I Press button Create of New Deploy key show error 500
I view product.log 
Errno::ENOENT (No such file or directory - ssh):
  lib/gitlab/popen.rb:23:in `popen'
  lib/gitlab/key_fingerprint.rb:42:in `explicit_fingerprint_algorithm?'
  lib/gitlab/key_fingerprint.rb:21:in `block in fingerprint'
  lib/gitlab/key_fingerprint.rb:15:in `fingerprint'
  app/models/key.rb:85:in `generate_fingerprint'
  app/controllers/projects/deploy_keys_controller.rb:34:in `create'

**Comment by manhnv85** [comment]
I fixed by 
sudo yum install openssh-server openssh-clients
