### ISSUE TITLE
I can't delete projects after upgrading gitlab to 7.7.1

### ISSUE THREAD

**Issue by crocket** [gitlabhq/gitlabhq#8671]
I see the following error in production.log when I try to delete a project.

```
Started DELETE "/templates/minimal-react-example" for 127.0.0.1 at 2015-01-28 17:54:51 +0900
Processing by ProjectsController#destroy as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"8aU/BtqP1HggIh2LsTsxIG61dddpaP8xApsgbIlkUl0=", "id"=>"templates/minimal-react-example"}
Completed 500 Internal Server Error in 57ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/services/projects/destroy_service.rb:9:in `execute'
  app/controllers/projects_controller.rb:86:in `destroy'
```

What's wrong?

**Comment by Razer6** [comment]
Which ruby version are you using? 2.2.0 is currently not supported.

**Comment by crocket** [comment]
I use ruby 2.2.0 because archlinux moved to 2.2.0.
I tried to use RVM, but it wasn't easy because lots of ruby scripts refer to /usr/bin/ruby directly.

**Comment by Razer6** [comment]
Yes this issue is most probably related to ruby 2.2
