### ISSUE TITLE
500 error when saving a wiki page with "." in title after 6.9.0

### ISSUE THREAD

**Issue by taiyangc** [gitlabhq/gitlabhq#7035]
**Summary:** For a new wiki page with dot (".") in the title, creation succeeds, but saving results in a 500 error.
**Steps to reproduce:**
    1. Select a repo, click "Wiki"
    2. Click "New Page"
    3. In the popup window, put in a title with "." in it
    4. Click "Build"
    5. Input some text & commit message
    6. Click "Create Page"
**Expected behavior:** Should just save the wiki page. 
**Observed behavior:** 500 error happens. If navigating back to Pages, a new page is created. In the actual .wiki.git a correct markdown file is available. If this new page is selected, a new editing window opens, not displaying the content just saved. Dot-titled wiki page worked in 6.8.* but stopped working in 6.9.0. Upgrading to 6.9.1 has the same result.
**Relevant logs and/or screenshots:** 
```
43792 Started POST "/taiyangc/homerrouter/wikis" for 127.0.0.1 at 2014-05-28 23:46:35 +0800
43793 Processing by Projects::WikisController#create as HTML
43794   Parameters: {"utf8"=>"✓", "authenticity_token"=>"TpyEkgcBFK9oQmU1RMjuD/RtIMSd1UdHVnp6wRBobdI=", "wiki"=>{"title"=>"Router_Te.st", "format"=>"markdown", "content"=>"aaa", "message"=>"Test"}, "project_id"=>"taiyangc/homerrouter"}
43795 Completed 500 Internal Server Error in 32ms
43796
43797 NoMethodError (undefined method `escaped_url_path' for nil:NilClass):
43798   app/models/wiki_page.rb:172:in `set_attributes'
43799   app/models/wiki_page.rb:191:in `save'
43800   app/models/wiki_page.rb:139:in `create'
43801   app/controllers/projects/wikis_controller.rb:59:in `create'
43802   app/controllers/application_controller.rb:59:in `set_current_user_for_thread'
```
**Output of checks:**
    1. Version of GitLab: 6.9.1.
    2. Add the last commit sha1 of the GitLab version you used to replicate the issue (obtainable from the help page): 13202d8
    3. Results of GitLab [Application Check](doc/install/installation.md#check-application-status):
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.4 ? ... OK (1.9.4)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
Eric Chen / homerrouter ... ok
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.9
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
Eric Chen / homerrouter ... yes
Projects have satellites? ... 
Eric Chen / homerrouter ... yes
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.3)

Checking GitLab ... Finished
``` 
**Possible fixes**: Not sure.

**Comment by Razer6** [comment]
Fixed with https://github.com/gitlabhq/gitlabhq/commit/1d85e5fffff66e5b074480d91b414968955b1ee5
