### ISSUE TITLE
500 errors when upgrade to v7.8.1

### ISSUE THREAD

**Issue by jieer** [gitlabhq/gitlabhq#8864]
Started GET "/" for xx.xx.xx.xx at 2015-02-25 21:13:54 +0800
Processing by DashboardController#show as HTML
Completed 500 Internal Server Error in 135ms

NameError (undefined local variable or method `template' for #<GitlabIssueTrackerService:0x007f7acca8c908>):
  app/models/service.rb:37:in `template?'
  app/models/service.rb:28:in `block in <class:Service>'
  app/models/project.rb:324:in `default_issue_tracker'
  app/controllers/application_controller.rb:184:in `add_gon_variables'

**Comment by jf1603** [comment]
Same here. 
OS Ubuntu 14.04.1

````
Processing by SessionsController#new as HTML
Completed 500 Internal Server Error in 122ms

NameError (undefined local variable or method `template' for #<GitlabIssueTrackerService:0x000000061c5da8>):
  app/models/service.rb:37:in `template?'
  app/models/service.rb:28:in `block in <class:Service>'
  app/models/project.rb:324:in `default_issue_tracker'
  app/controllers/application_controller.rb:184:in `add_gon_variables'
````

**Comment by Razer6** [comment]
@jieer @jf1603 From which version are you upgrading from?

**Comment by Razer6** [comment]
@jieer @jf1603 Can you try rerunning the database migration again?

**Comment by jf1603** [comment]
Did just that - after database migration everything seems to work. Thank you!

**Comment by vflong** [comment]
v7.7.2 to v7.8.1
# gitlab-ctl reconfigure
 Starting Chef Client, version 11.12.2
Compiling Cookbooks...
Recipe: gitlab::default
  * directory[/etc/gitlab] action create (up to date)
[2015-02-26T10:19:11+08:00] WARN: Cloning resource attributes for directory[/var/opt/gitlab] from prior resource (CHEF-3694)
[2015-02-26T10:19:11+08:00] WARN: Previous directory[/var/opt/gitlab]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/default.rb:40:in `from_file'
[2015-02-26T10:19:11+08:00] WARN: Current  directory[/var/opt/gitlab]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/users.rb:23:in `from_file'
[2015-02-26T10:19:12+08:00] WARN: Cloning resource attributes for group[gitlab-redis] from prior resource (CHEF-3694)
[2015-02-26T10:19:12+08:00] WARN: Previous group[gitlab-redis]: /opt/gitlab/embedded/cookbooks/gitlab/definitions/redis_service.rb:25:in `block in from_file'
[2015-02-26T10:19:12+08:00] WARN: Current  group[gitlab-redis]: /opt/gitlab/embedded/cookbooks/gitlab/definitions/redis_service.rb:25:in `block in from_file'
[2015-02-26T10:19:12+08:00] WARN: Cloning resource attributes for user[gitlab-redis] from prior resource (CHEF-3694)
[2015-02-26T10:19:12+08:00] WARN: Previous user[gitlab-redis]: /opt/gitlab/embedded/cookbooks/gitlab/definitions/redis_service.rb:30:in `block in from_file'
[2015-02-26T10:19:12+08:00] WARN: Current  user[gitlab-redis]: /opt/gitlab/embedded/cookbooks/gitlab/definitions/redis_service.rb:30:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Cloning resource attributes for directory[/var/opt/gitlab/gitlab-rails/etc] from prior resource (CHEF-3694)
[2015-02-26T10:19:13+08:00] WARN: Previous directory[/var/opt/gitlab/gitlab-rails/etc]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/gitlab-rails.rb:41:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Current  directory[/var/opt/gitlab/gitlab-rails/etc]: /opt/gitlab/embedded/cookbooks/gitlab/definitions/unicorn_config.rb:21:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Cloning resource attributes for service[unicorn] from prior resource (CHEF-3694)
[2015-02-26T10:19:13+08:00] WARN: Previous service[unicorn]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/default.rb:78:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Current  service[unicorn]: /opt/gitlab/embedded/cookbooks/runit/definitions/runit_service.rb:191:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Cloning resource attributes for directory[/var/opt/gitlab/gitlab-ci/etc] from prior resource (CHEF-3694)
[2015-02-26T10:19:13+08:00] WARN: Previous directory[/var/opt/gitlab/gitlab-ci/etc]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/gitlab-ci.rb:52:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Current  directory[/var/opt/gitlab/gitlab-ci/etc]: /opt/gitlab/embedded/cookbooks/gitlab/definitions/unicorn_config.rb:21:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Cloning resource attributes for service[ci-unicorn] from prior resource (CHEF-3694)
[2015-02-26T10:19:13+08:00] WARN: Previous service[ci-unicorn]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/default.rb:78:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Current  service[ci-unicorn]: /opt/gitlab/embedded/cookbooks/runit/definitions/runit_service.rb:191:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Cloning resource attributes for service[sidekiq] from prior resource (CHEF-3694)
[2015-02-26T10:19:13+08:00] WARN: Previous service[sidekiq]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/default.rb:78:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Current  service[sidekiq]: /opt/gitlab/embedded/cookbooks/runit/definitions/runit_service.rb:191:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Cloning resource attributes for service[ci-sidekiq] from prior resource (CHEF-3694)
[2015-02-26T10:19:13+08:00] WARN: Previous service[ci-sidekiq]: /opt/gitlab/embedded/cookbooks/gitlab/recipes/default.rb:78:in `block in from_file'
[2015-02-26T10:19:13+08:00] WARN: Current  service[ci-sidekiq]: /opt/gitlab/embedded/cookbooks/runit/definitions/runit_service.rb:191:in `block in from_file'





gitlab-rake db:migrate
-- add_column(:merge_requests, :position, :integer, {:default=>0})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::Error: ERROR:  column "position" of relation "merge_requests" already exists
: ALTER TABLE "merge_requests" ADD COLUMN "position" integer DEFAULT 0
ActiveRecord::StatementInvalid: PG::Error: ERROR:  column "position" of relation "merge_requests" already exists
: ALTER TABLE "merge_requests" ADD COLUMN "position" integer DEFAULT 0

PG::Error: ERROR:  column "position" of relation "merge_requests" already exists

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by vflong** [comment]
@Razer6 
v7.7.2 to v7.8.1
"gitlab-rake db:migrate" has some errors

**Comment by Razer6** [comment]
For the omnibus package please head over to the omnibus repository: https://gitlab.com/gitlab-org/omnibus-gitlab
