### ISSUE TITLE
Gitlab 7.9.2 ruby 2.1.5 protected branches error 500 on any project

### ISSUE THREAD

**Issue by gojkop** [gitlabhq/gitlabhq#9081]
When pressing protected branches on any project in settings i get this in log even with new projects:

Started GET "/root/gojko/protected_branches" for 127.0.0.1 at 2015-04-02 17:42:09 +0200
Processing by Projects::ProtectedBranchesController#index as HTML
  Parameters: {"namespace_id"=>"root", "project_id"=>"gojko"}
Completed 500 Internal Server Error in 34ms

ActionView::Template::Error (undefined method `developers_can_push' for #<ProtectedBranch:0x007f143d2539a8>):

Tried with ruby 2.0 and it did not help. This was working in 7.6
Also i have nginx and mysql in settup. And this is Centos 6.6 without selinux.
Also i am not sure if content of mysql table protected_branch should be empty.

**Comment by stanhu** [comment]
This sounds like you are missing database migrations. If you are using the omnibus version, take a look here:

https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/update.md

Make sure your DB is running before you run `gitlab-ctl reconfigure`.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
