### ISSUE TITLE
500 error on directory where submodule is located

### ISSUE THREAD

**Issue by N3XT0R** [gitlabhq/gitlabhq#8881]
Hello Guys,

i had created in gitlab a repository for a module for a Project, this Repository i had registered inside another project as a submodule. 

So when i trying to get the modules Directory view inside the Gitlab WebGUI, than appears a 500 error.

Log:

```
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"ib/xconf-2-reseller", "id"=>"develop/module"}
Completed 500 Internal Server Error in 42ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: %tr{ class: "tree-item" }
    2:   %td.tree-item-file-name
    3:     %i.fa.fa-archive
    4:     = submodule_link(submodule_item, @ref)
    5:   %td
    6:   %td.hidden-xs
  app/models/repository.rb:169:in `method_missing'
  app/models/repository.rb:231:in `submodule_url_for'
  app/helpers/submodule_helper.rb:6:in `submodule_links'
  app/helpers/diff_helper.rb:140:in `submodule_link'
  app/views/projects/tree/_submodule_item.html.haml:4:in `_app_views_projects_tree__submodule_item_html_haml___2297852807308961645_70276729045800'
  app/helpers/tree_helper.rb:21:in `render_tree'
  app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml__2635487318074036461_70276661599920'
  app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__699860618868555603_70276656514200'
  app/controllers/projects/tree_controller.rb:18:in `show'

```

i am using the Gitlab Version 7.8.1

**Comment by elboletaire** [comment]
Same here....

- GitLab 7.8.1
- GitLab Shell 2.5.4
- GitLab API v3
- Ruby 2.1.2p95
- Rails 4.1.1 

Log...
```
Started GET "/projects/web/tree/r/project/app/plugins" for 127.0.0.1 at 2015-03-03 10:22:54 +0100
Processing by Projects::TreeController#show as HTML
Parameters: {"project_id"=>"projects/web", "id"=>"r/project/app/plugins"}
Completed 500 Internal Server Error in 60ms
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
1: %tr{ class: "tree-item" }
2: %td.tree-item-file-name
3: %i.fa.fa-archive
4: = submodule_link(submodule_item, @ref)
5: %td
6: %td.hidden-xs
app/models/repository.rb:169:in `method_missing'
app/models/repository.rb:231:in `submodule_url_for'
app/helpers/submodule_helper.rb:6:in `submodule_links'
app/helpers/diff_helper.rb:140:in `submodule_link'
app/views/projects/tree/_submodule_item.html.haml:4:in `_app_views_projects_tree__submodule_item_html_haml___757825597062475290_69974009224620'
app/helpers/tree_helper.rb:21:in `render_tree'
app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml___3163902857773330229_69974007705300'
app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__812308402577581816_69974005839840'
app/controllers/projects/tree_controller.rb:18:in `show'
```

**Comment by elboletaire** [comment]
In my case is not always. I've some projects with submodules which I can list without problems. Some of these plugins cannot be seen from other project pages, where I get the above error.

**Comment by pelallemant** [comment]
Same error when I did the following steps:
- modify a submodule
- commit the submodule, I didnt push it (by error)
- I commit / push the main project
- I go on gitlab to check commit, and error 500

I pushed the submodule, but it doesnt works for the commit of the main project I did.
I dont have the error 500 on other commits.

**Comment by creker** [comment]
Same error on 7.9.0
```
Started GET "/group/project/tree/master" for 127.0.0.1 at 2015-03-26 20:07:22 +0400
Processing by Projects::TreeController#show as HTML
Parameters: {"namespace_id"=>"group", "project_id"=>"project", "id"=>"master"}
Completed 500 Internal Server Error in 53ms
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
1: %tr{ class: "tree-item" }
2: %td.tree-item-file-name
3: %i.fa.fa-archive
4: = submodule_link(submodule_item, @ref)
5: %td
6: %td.hidden-xs
app/models/repository.rb:170:in `method_missing'
app/models/repository.rb:232:in `submodule_url_for'
app/helpers/submodule_helper.rb:6:in `submodule_links'
app/helpers/diff_helper.rb:140:in `submodule_link'
app/views/projects/tree/_submodule_item.html.haml:4:in `_app_views_projects_tree__submodule_item_html_haml__1655226601875517539_115242420'
app/helpers/tree_helper.rb:21:in `render_tree'
app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml___747719611893895485_45291800'
app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml___1946431578612287978_43791940'
app/controllers/projects/tree_controller.rb:21:in `show'
```

**Comment by creker** [comment]
#9005 says problem gone after updating to 7.9.1. Didn't help for me - still the same error

**Comment by mr-vinn** [comment]
@N3XT0R, @creker, @pelallemant, @elboletaire If anyone has a public repo that displays this behavior, or can easily create one, please post the URL here.  I'll take another look at the gitlab_git gem's submodule code to try and fix this.

**Comment by elboletaire** [comment]
I cannot, sorry.. my gitlab is in a LAN.

But I can confirm the behavior described by @pelallemant. It only occurs when you accidentally commit a submodule that is not under the git cache.

**Comment by creker** [comment]
Sorry, my gitlab is in LAN too

**Comment by zidnut** [comment]
https://gitlab.kitware.com/paraview/paraview/merge_requests/9/diffs

**Comment by sublee** [comment]
I have same issue on GitLab 7.9.1.

**Comment by stanhu** [comment]
I submitted a fix here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/508

**Comment by DouweM** [comment]
Fixed by 6331759735074e2b14d398dfa1804cfa1f241d49!

**Comment by elboletaire** [comment]
@DouweM could you, please, add a link to that commit? I can't find it...

https://github.com/gitlabhq/gitlabhq/commit/6331759735074e2b14d398dfa1804cfa1f241d49

**Comment by rumpelsepp** [comment]
Most likely not merged into github yet: https://gitlab.com/gitlab-org/gitlab-ce/commit/6331759735074e2b14d398dfa1804cfa1f241d49

**Comment by stanhu** [comment]
Upon further review, I'm not sure if my fix addresses this particular problem. I did just try the flow mentioned by @pelallemant both with submodules that had relative URLs and ones that did not. Instead of a 500 error, I got an expected 404 since the commit for the submodule did not exist. The link to the submodule itself looked fine.

Can somebody who is having this issue retest this, either with master or v7.10 when it is released on the 22nd?

**Comment by creker** [comment]
In my case submodules didn't have relative links. As soon as 7.10 releases I will test it and report here

**Comment by sublee** [comment]
I also don't use relative link for submodules.

**Comment by stanhu** [comment]
Despite trying a number of approaches, I still haven't been able to reproduce this on the master branch (7d089701f1a9c15117e3e2d6f21eabaf08659ff6). It looks like the error described above can only happen if GitLab is unable to find the blob for the commit and the submodule path. I'm not sure how that can happen in normal situations. Even if you bump the version of a submodule before pushing the submodule itself, the resulting commit still has a valid ID and file reference. Even when I did a rebase and force push, I was still able to see the commit in GitLab.

For those having the issue now, what happens when you do a `git show <commit ID>`? Is it possible the repository has been corrupted somehow?

**Comment by stanhu** [comment]
For those of you hitting this error, can you paste your `.gitmodules`? I definitely found an issue where adding comments or some stray lines at the end caused this error. If you prefer not to share this file, please see whether it contains such lines.

Thanks to @sublee for helping debug the issue:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1412

Proposed fix here:

https://gitlab.com/gitlab-org/gitlab-git-test/merge_requests/4

**Comment by creker** [comment]
Here is my .gitmodules. I don't know for sure which one causes the problem but after they've been commited commit history is broken.
```
0000-0010:  5b 73 75 62-6d 6f 64 75-6c 65 20 22-6d 31 22 5d  [submodu le."m1"]
0000-0020:  0d 0a 09 70-61 74 68 20-3d 20 6d 31-0a 09 75 72  ...path. =.m1..ur
0000-0030:  6c 20 3d 20-68 74 74 70-73 3a 2f 2f-64 6f 6d 61  l.=.http s://doma
0000-0040:  69 6e 2f 6d-31 2e 67 69-74 0a 5b 73-75 62 6d 6f  in/m1.gi t.[submo
0000-0050:  64 75 6c 65-20 22 6d 32-22 5d 0a 09-70 61 74 68  dule."m2 "]..path
0000-0060:  20 3d 20 6d-32 0a 09 75-72 6c 20 3d-20 68 74 74  .=.m2..u rl.=.htt
0000-0070:  70 73 3a 2f-2f 64 6f 6d-61 69 6e 2f-6d 32 2e 67  ps://dom ain/m2.g
0000-0080:  69 74 0a 5b-73 75 62 6d-6f 64 75 6c-65 20 22 6d  it.[subm odule."m
0000-0090:  33 22 5d 0d-0a 09 70 61-74 68 20 3d-20 6d 33 0a  3"]...pa th.=.m3.
0000-00a0:  09 75 72 6c-20 3d 20 68-74 74 70 73-3a 2f 2f 64  .url.=.h ttps://d
0000-00b0:  6f 6d 61 69-6e 2f 6d 33-2e 67 69 74-0a 09 0d 0a  omain/m3 .git....
0000-00b1:  09
```
```
0000-0010:  5b 73 75 62-6d 6f 64 75-6c 65 20 22-6d 31 22 5d  [submodu le."m1"]
0000-0020:  0d 0a 09 70-61 74 68 20-3d 20 6d 31-0a 09 75 72  ...path. =.m1..ur
0000-0030:  6c 20 3d 20-68 74 74 70-73 3a 2f 2f-64 6f 6d 61  l.=.http s://doma
0000-0040:  69 6e 2f 6d-31 2e 67 69-74 0a 5b 73-75 62 6d 6f  in/m1.gi t.[submo
0000-0050:  64 75 6c 65-20 22 6d 32-22 5d 0a 09-70 61 74 68  dule."m2 "]..path
0000-0060:  20 3d 20 6d-32 0a 09 75-72 6c 20 3d-20 68 74 74  .=.m2..u rl.=.htt
0000-0070:  70 73 3a 2f-2f 64 6f 6d-61 69 6e 2f-6d 32 2e 67  ps://dom ain/m2.g
0000-0080:  69 74 0a 5b-73 75 62 6d-6f 64 75 6c-65 20 22 6d  it.[subm odule."m
0000-0090:  33 22 5d 0d-0a 09 70 61-74 68 20 3d-20 6d 33 0d  3"]...pa th.=.m3.
0000-00a0:  0a 09 75 72-6c 20 3d 20-68 74 74 70-73 3a 2f 2f  ..url.=. https://
0000-00b0:  64 6f 6d 61-69 6e 2f 6d-33 2e 67 69-74 0d 0a 09  domain/m 3.git...
0000-00b3:  0d 0a 09
```

**Comment by stanhu** [comment]
@creker, thanks for the hex dump! I just verified that the issue is the trailing 0x09 (horizontal tab) is causing the parser to hit this error. Looks like my fix will correct this issue. The gitlab_git changes to fix this will be merged in tomorrow. @DouweM, any chance this can land in GitLab v7.10?

**Comment by DouweM** [comment]
@stanhu I'll merge your patch tomorrow and I'll try to get it in the next RC.

**Comment by stanhu** [comment]
Woohoo! Thanks, @DouweM. I'm sure everyone here appreciates the effort.
