### ISSUE TITLE
Admin page 500s after update to 7.10

### ISSUE THREAD

**Issue by andyjeffries** [gitlabhq/gitlabhq#9176]
```
Started GET "/admin" for 127.0.0.1 at 2015-04-23 10:21:41 +0100
Processing by Admin::DashboardController#index as HTML
Completed 500 Internal Server Error in 272ms

ActionView::Template::Error (undefined local variable or method `admin_deploy_keys_path' for #<#<Class:0x007f3ba817dcd0>:0x007f3ba7ca49e8>):
    20:       %span
    21:         Groups
    22:   = nav_link(controller: :deploy_keys) do
    23:     = link_to admin_deploy_keys_path, title: 'Deploy Keys' do
    24:       %i.fa.fa-key
    25:       %span
    26:         Deploy Keys
  app/views/layouts/nav/_admin.html.haml:23:in `block in _app_views_layouts_nav__admin_html_haml__1933874017632518056_69947099253440'
  app/helpers/tab_helper.rb:55:in `nav_link'
  app/views/layouts/nav/_admin.html.haml:22:in `_app_views_layouts_nav__admin_html_haml__1933874017632518056_69947099253440'
  app/views/layouts/_page.html.haml:5:in `_app_views_layouts__page_html_haml__1040612682301672625_69947099578740'
  app/views/layouts/admin.html.haml:6:in `_app_views_layouts_admin_html_haml___497888448711239772_69947099991160'

```

**Comment by DouweM** [comment]
@andyjeffries I can't reproduce this issue. Have you tried restarting GitLab?

**Comment by JobV** [comment]
Could also be a missed migration. If restarting doesn't work, try running reconfigure again.

**Comment by stanhu** [comment]
I wonder if a permission issue on files could be the problem? A user had a similar issue with missed migrations:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1492

**Comment by DouweM** [comment]
@stanhu A permission issue on `config/routes.rb` could cause this, sure.

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
