### ISSUE TITLE
After upgrading from 7.10 to 7.14.3-ce.0 on Ubuntu, LDAP login fails with Pg::undefinedTable error

### ISSUE THREAD

**Issue by PredatorVI** [gitlabhq/gitlabhq#9652]
Ubuntu 14.04.03 LTS

After inadvertently running the apt-get update/upgrade process to fix a different package issue (unrelated to gitlab), GitLab no long will authenticate via LDAP or local user.  I think a table is missing something.  If I disable LDAP and try the default user, I get a 500 error:

LDAP error from UI:
```
Could not authorize you from Ldapmain because "Pg::undefinedtable: error: relation "audit events" does not exist Line 5: where a.attrelid = '"audit events"'::regclass ^ : select a.attname, format type(a.atttypid, a.atttypmod), pg get expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod from pg attribute a left join pg attrdef d on a.attrelid = d.adrelid and a.attnum = d.adnum where a.attrelid = '"audit events"'::regclass and a.attnum > 0 and not a.attisdropped order by a.attnum ".
```
LOG error using default user:
```
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"login"=>"root", "password"=>"[FILTERED]", "remember_me"=>"0"}}
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.3ms)

NoMethodError (undefined method `otp_required_for_login?' for #<User:0x0000000c196818>):
  app/controllers/sessions_controller.rb:65:in `authenticate_with_two_factor'
```

**Comment by oshanz** [comment]
same here. configuration files also restored
ubuntu 14, gitlab 7.10.1 to 7.14.3

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
